site_name: Rafael Leone

theme:
  name: material

site_url: https://rafaelleone.github.io/mkdocs_curriculo/
repo_url: https://github.com/RafaelLeone/mkdocs_curriculo

nav:
    - Início: 'index.md'
    - Sobre:
        - 'Cumprimentos': 'about/about.md'
        - 'Perguntas': 'about/about2.md'

extra_css:
  - stylesheets/extra.css
